# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('orignal_duration', models.IntegerField()),
                ('orignal_resources', models.IntegerField()),
                ('orignal_cost', models.IntegerField()),
                ('additional_resources', models.IntegerField()),
                ('additional_cost', models.IntegerField()),
                ('crash_duration_days', models.IntegerField()),
                ('time_saved', models.IntegerField()),
                ('total_cost', models.IntegerField()),
            ],
        ),
    ]
